### ISSUE TITLE
migration support

### ISSUE THREAD

**Issue by mattgi** [bentojs/api-mysql#3]
create migrations based on http://docs.sequelizejs.com/en/latest/docs/migrations/ in bento. This may require its own standalone cli (or perhaps sequelize-cli will just work for bento)

**Comment by Kodemon** [comment]
@mattgi It seems that the sequelize-cli should just work out of the box since you have to be creating the migration scripts manually either way. Seems sequelize migration would just work on any mysql based database.

**Comment by Kodemon** [comment]
re-open at a later date, this won't be happening for quite some time. Best approach now is to write custom outside migration scripts for larger migration operations or do the migrations manually in the database.
