### ISSUE TITLE
schema default limit definition

### ISSUE THREAD

**Issue by mattgi** [bentojs/api-mysql#6]
allow a default limit to be set when defining a model's schema:

```
Bento.Register.Model('User', 'sequelize', (model, Sequelize) => {
  ...
  model.limit = 200;
  ...
});
```

**Comment by mattgi** [comment]
In my current project, the timeline view requires all users to be listed as rows. As there will never be more than ~50 users (per group) making several (paged) requests for this data is not realistic or required.

Whilst the fix could be done in the service, this specific issue relates to `users` and it is using the bento provided `user module`. As such, we need a way to set up the limit for user without forking the `user-module`. As the User model lives in the project's interface, this is something that we could easily set up in here.

For reference, we could pass a limit from the client as well.. but as we want to just allow 200 user records no matter where it is being consumed from, it makes sense to put it on the model.

**Comment by Kodemon** [comment]
Query parser no longer sets auto limits on queries, you now assign them in the **model.filter** method if you want to set custom default limits.
